<?php

/**
 * ProcessWire Hot Key Search module
 * By Robin Sallis
 * Based largely on AdminHotKeys by "Soma" Philipp Urlich
 *
 * Adds configurable hot keys for easier use of the admin search via the keyboard.
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class ProcessHotKeySearch extends WireData implements Module, ConfigurableModule {

	public static function getModuleInfo() {

		return array(
			'title' => 'Hot Key Search',
			'version' => 2,
			'summary' => 'Adds configurable hot keys for easier use of the admin search via the keyboard.',
			'singular' => true,
			'autoload' => 'admin'
		);
	}

	protected static $defaults = array(
		'key_search' => 's',
		'key_trigger' => 'enter'
	);

	public function init() {

		// add js config to admin output
		$config = self::$defaults;
		foreach($config as $key => $unused) $config[$key] = $this->get($key) == null ? $config[$key] : $this->get($key);

		$this->config->js($this->className(), $config);

		// add hook to add scripts
		if(strpos($_SERVER["REQUEST_URI"], $this->config->urls->admin) !== false){
			$this->addHookAfter('Process::execute', $this, 'addHksScripts');
			$this->addHookAfter('Process::executeEdit', $this, 'addHksScripts');
		}
	}

	public function addHksScripts(HookEvent $event) {
		// if on login no need to go further
		if($this->process == 'ProcessLogin') return;
		$conf = $this->getModuleInfo();
		$version = (int) $conf['version'];
		$this->config->scripts->add($this->config->urls->ProcessHotKeySearch . "mousetrap.min.js?v={$version}");
		$this->config->scripts->add($this->config->urls->ProcessHotKeySearch . "ProcessHotKeySearch.js?v={$version}");
	}

	static public function getModuleConfigInputfields(array $data) {
		$data = array_merge(self::$defaults, $data);

		$fields = new InputfieldWrapper();
		$modules = wire('modules');

		$field = $modules->get('InputfieldMarkup');
		$field->attr('name', 'info');
		$field->label = "Info";
		$markup = "
		<p>This module uses Mousetrap for key bindings. See the <a href='https://craig.is/killing/mice' target='_blank'>documentation</a> for supported keys.</p>
		";
		$field->attr('value', $markup);
		$fields->append($field);

		$field = $modules->get('InputfieldText');
		$field->attr('name', 'key_search');
		$field->attr('size', 15);
		$field->attr('value', $data['key_search']);
		$field->label = "Search";
		$field->description = "Hot key to toggle scroll/focus to search.";
		$fields->append($field);

		$field = $modules->get('InputfieldText');
		$field->attr('name', 'key_trigger');
		$field->attr('size', 15);
		$field->attr('value', $data['key_trigger']);
		$field->label = "Trigger result";
		$field->description = "Hot key to trigger link of focused search result.";
		$fields->append($field);

		return $fields;
	}

}
